### ISSUE TITLE
Got this error on Termux

### ISSUE THREAD

**Issue by Lucky-069** [gnuhead-chieb/revanced-automatic-builder#1]
INFO: promo-code-unlock succeeded
INFO: Compiling resources
WARNING: /data/data/com.termux/files/usr/tmp/brut_util_Jar_680093943790371303444458820342444688.tmp: no closing quote
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_680093943790371303444458820342444688.tmp, compile, --dir, /data/data/com.termux/files/home/.revanced/revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/.revanced/revanced-cache/build/resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:372)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:204)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_680093943790371303444458820342444688.tmp, compile, --dir, /data/data/com.termux/files/home/.revanced/revanced-cache/res, --legacy, -o, /data/data/com.termux/files/home/.revanced/revanced-cache/build/resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:368)
        ... 13 more
mv: cannot stat 'warnwetter-patched.apk': No such file or directory
mv: cannot stat '/data/data/com.termux/files/home/warnwetter-patched.apk': No such file or directory

**Comment by gnuhead-chieb** [comment]
fixed in https://github.com/gnuhead-chieb/revanced-automatic-builder/commit/119a20e97716db9065d38f3436842dd66c76e748

**Comment by Lucky-069** [comment]
Still throws the same error.. I even purged the directory and did a fresh install. For some reason the error is same.

**Comment by gnuhead-chieb** [comment]
![Screenshot_20220811-174054_パッケージ インストーラ](https://user-images.githubusercontent.com/41156994/184096086-3dc747e5-7214-48fd-b96e-ce0e1551a577.png)
works on my side, many warns with white color can be ignored.

**Comment by gnuhead-chieb** [comment]
are you using NON arm64-v8a phone?

**Comment by Lucky-069** [comment]
WARNING: /data/data/com.termux/files/home/.revanced/revanced-cache/AndroidManifest.xml:555: error: unexpected element <uses-native-library> found in <manifest><application>.
WARNING: /data/data/com.termux/files/home/.revanced/revanced-cache/AndroidManifest.xml:556: error: unexpected element <uses-native-library> found in <manifest><application>.
WARNING: /data/data/com.termux/files/home/.revanced/revanced-cache/AndroidManifest.xml:557: error: unexpected element <uses-native-library> found in <manifest><application>.
WARNING: /data/data/com.termux/files/home/.revanced/revanced-cache/AndroidManifest.xml:558: error: unexpected element <uses-native-library> found in <manifest><application>.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/.revanced/revanced-cache/aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 32, --version-code, 548620, --version-name, 2022.30.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL274359155676817920.tmp, -0, arsc, -I, revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/.revanced/revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/.revanced/revanced-cache/build/resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:204)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/.revanced/revanced-cache/aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 32, --version-code, 548620, --version-name, 2022.30.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL274359155676817920.tmp, -0, arsc, -I, revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/.revanced/revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/.revanced/revanced-cache/build/resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more
mv: cannot stat 'reddit-patched.apk': No such file or directory
mv: cannot stat '/data/data/com.termux/files/home/reddit-patched.apk': No such file or directory
Your patched apk was saved in "/storage/emulated/0/"

**Comment by Lucky-069** [comment]
> are you using NON arm64-v8a phone?

Nope I'm on A11, arm64-v8a phone!

**Comment by Lucky-069** [comment]
Okay, I had to reinstall termux again and I did a fresh install, it worked with warnwetter, I have yet to try reddit apk

**Comment by Lucky-069** [comment]
Try building reddit. Warn wetter gets built but not reddit or Twitter.

**Comment by gnuhead-chieb** [comment]
Ah yeah,it seems due to aapt2 limitation on Android.
Probably works on proot-distro over termux but not tested.
I will investigate this problem in my free time, in the mean time,i kept this issue open.

**Comment by gnuhead-chieb** [comment]
It seems this issue fixed for now by on their side
